# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 670fb1627a58264df336d6571fed363172fdf8b455f706c28a195145d5153cb285576671fee619c3ab032807b47e09adbb4e797f57b67e95fc44dfbca05e7d40

test:
  secret_key_base: 7db132099d23db0c601cb2d23f221234a91f89576ad670b1e661eb6a344e7532c229c08cb7a4359f35e73484d9fbd0d4fb46f183d9abea5b0efe6e98b8158363

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
